version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: C@L@BR3S0
      MYSQL_DATABASE: seth
      MYSQL_USER: devlocal
      MYSQL_PASSWORD: devlocal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: my_adminer
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
